#ifndef PINSETUP_H_
#define PINSETUP_H_

#define PIN_FRONT_RATO 12
#define PIN_BACK_RATO 10

#define PIN_FRONT_LEFT_MAGNETS 2
#define PIN_FRONT_RIGHT_MAGNETS 4
#define PIN_BACK_LEFT_MAGNETS 6
#define PIN_BACK_RIGHT_MAGNETS 8

#define PIN_FRONT_ELEVATOR_STEP 0
#define PIN_FRONT_ELEVATOR_DIR 0
#define PIN_BACK_ELEVATOR_STEP 0
#define PIN_BACK_ELEVATOR_DIR 0

#endif